# This is a basic workflow to help you get started with Actions

name: Hydejack Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Branch
        # You may pin to the exact commit or the version.
        # uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The branch to create
          branch: hydejack-update

      # Runs a set of commands using the runners shell
      - name: Bundle Update
        run: |
          gem i bundler
          bundle i
          bundle update jekyll-theme-hydejack

      - name: Create Pull Request
        # You may pin to the exact commit or the version.
        # uses: quangvo09/create-pull-request-action@a5dbb8ea69f7809706817d0057d8a7901fde30a2
        uses: quangvo09/create-pull-request-action@v1.0.1
        with:
          # GitHub token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Run action on branch with prefix
          branch_prefix: hydejack-update
          # base branch for create pr
          base_branch: master
          # pull request assignees
          assignees: ThomasIAm
